homepage:
    pattern:  /
    defaults: { _controller: MrmcburgerGetajobBundle:Home:index }

getajob_bundle:
    resource: "@MrmcburgerGetajobBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
