mrmcburger_getajob_homepage:
    pattern:  /
    defaults: { _controller: MrmcburgerGetajobBundle:Home:index }

mrmcburger_getajob_new_company:
    pattern:  /newcompany
    defaults: { _controller: MrmcburgerGetajobBundle:Company:new }

mrmcburger_getajob_show_company:
    pattern:  /showcompany/{id}
    defaults: { _controller: MrmcburgerGetajobBundle:Company:show }

mrmcburger_getajob_modify_company:
    pattern:  /modifycompany/{id}
    defaults: { _controller: MrmcburgerGetajobBundle:Company:modify }

mrmcburger_getajob_delete_company:
    pattern:  /deletecompany
    defaults: { _controller: MrmcburgerGetajobBundle:Company:delete }

mrmcburger_getajob_list_company:
    pattern:  /listcompanies/{page}
    defaults: { _controller: MrmcburgerGetajobBundle:Company:list }

mrmcburger_getajob_rank_company:
    pattern:  /rankcompanies/{page}
    defaults: { _controller: MrmcburgerGetajobBundle:Company:rank }

mrmcburger_getajob_show_global_criteria:
    pattern:  /showglobalcriteria
    defaults: { _controller: MrmcburgerGetajobBundle:GlobalCriteria:show }

mrmcburger_getajob_modify_global_criteria:
    pattern:  /modifyglobalcriteria
    defaults: { _controller: MrmcburgerGetajobBundle:GlobalCriteria:modify }

mrmcburger_getajob_new_application:
    pattern:  /newapplication
    defaults: { _controller: MrmcburgerGetajobBundle:Application:new }

mrmcburger_getajob_show_application:
    pattern:  /showapplication/{id}
    defaults: { _controller: MrmcburgerGetajobBundle:Application:show }
