parameters:
    globalcriteria_manager.class: Mrmcburger\GetajobBundle\Services\GlobalCriteriaManager
    globalcriteria_factory.class: Mrmcburger\GetajobBundle\Services\GlobalCriteriaFactory
services:
    globalcriteria_factory:
        class:                  "%globalcriteria_factory.class%"
        arguments: [@doctrine.orm.entity_manager]
    globalcriteria_manager:
        class:                 "%globalcriteria_manager.class%"
        arguments: [@doctrine.orm.entity_manager]
        factory_service: globalcriteria_factory
        factory_method:   get
