<?php

namespace Mrmcburger\GetajobBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GlobalCriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalCriteriaRepository extends EntityRepository
{
}
