Feature: Company
    In order to be able to use the website
    As a website user
    I need to be able to do crud operations on company

Scenario: Company Access
    Given I am on "/newcompany"
    Then I should see "Ajouter une entreprise"

Scenario: Add a company
    Given I am on "/newcompany"
    When I fill in "mrmcburger_getajobbundle_companytype_name" with "BehatTest"
    And I fill in "mrmcburger_getajobbundle_companytype_sector" with "BehatTest Sector"
    And I fill in "mrmcburger_getajobbundle_companytype_address_number" with "12B"
    And I fill in "mrmcburger_getajobbundle_companytype_address_type" with "rue"
    And I fill in "mrmcburger_getajobbundle_companytype_address_name" with "BehatTest Address"
    And I fill in "mrmcburger_getajobbundle_companytype_address_additional" with "additional"
    And I fill in "mrmcburger_getajobbundle_companytype_address_zip" with "72"
    And I fill in "mrmcburger_getajobbundle_companytype_address_city" with "Behat"
    And I fill in "mrmcburger_getajobbundle_companytype_numbers" with "numbers"
    And I fill in "mrmcburger_getajobbundle_companytype_phone" with "phone"
    And I fill in "mrmcburger_getajobbundle_companytype_mail" with "mail@gmail.com"
    And I fill in "mrmcburger_getajobbundle_companytype_presentation" with "presentation"
    And I fill in "mrmcburger_getajobbundle_companytype_companycriteria_displacement" with "4"
    And I fill in "mrmcburger_getajobbundle_companytype_companycriteria_celebrity" with "6"
    And I fill in "mrmcburger_getajobbundle_companytype_companycriteria_missionInterest" with "7"
    And I fill in "mrmcburger_getajobbundle_companytype_companycriteria_salaryExpectation" with "8"
    And I fill in "mrmcburger_getajobbundle_companytype_companycriteria_workConditions" with "9"
    And I fill in "mrmcburger_getajobbundle_companytype_companycriteria_evolutionPossibilities" with "10"
    And I press "mrmcburger_getajobbundle_companytype_add_company"
    Then I should see "BehatTest"
    And I should see "BehatTest Sector"
    And I should see "12B"
    And I should see "rue"
    And I should see "additional"
    And I should see "72"
    And I should see "BehatTest Address"
    And I should see "numbers"
    And I should see "phone"
    And I should see "mail@gmail.com"
    And I should see "presentation"
    And I should see "4"
    And I should see "6"
    And I should see "7"
    And I should see "8"
    And I should see "9"
    And I should see "10"

Scenario: Add a company already existing
    Given I am on "/newcompany"
    When I fill in "mrmcburger_getajobbundle_companytype_name" with "BehatTest"
    And I fill in "mrmcburger_getajobbundle_companytype_sector" with "BehatTest Sector"
    And I fill in "mrmcburger_getajobbundle_companytype_address_number" with "12B"
    And I fill in "mrmcburger_getajobbundle_companytype_address_type" with "rue"
    And I fill in "mrmcburger_getajobbundle_companytype_address_name" with "BehatTestAddress"
    And I fill in "mrmcburger_getajobbundle_companytype_address_zip" with "72"
    And I fill in "mrmcburger_getajobbundle_companytype_address_city" with "Behat"
    And I press "mrmcburger_getajobbundle_companytype_add_company"
    Then I should see "Cette valeur est déjà utilisé"

Scenario: Add a company with a bad e-mail address
    Given I am on "/newcompany"
    When I fill in "mrmcburger_getajobbundle_companytype_name" with "Another Behat Test"
    And I fill in "mrmcburger_getajobbundle_companytype_sector" with "BehatTest Sector"
    And I fill in "mrmcburger_getajobbundle_companytype_address_number" with "12B"
    And I fill in "mrmcburger_getajobbundle_companytype_address_type" with "rue"
    And I fill in "mrmcburger_getajobbundle_companytype_address_name" with "BehatTestAddress"
    And I fill in "mrmcburger_getajobbundle_companytype_address_zip" with "72"
    And I fill in "mrmcburger_getajobbundle_companytype_address_city" with "Behat"
    And I fill in "mrmcburger_getajobbundle_companytype_mail" with "FakeAdressMail"
    And I press "mrmcburger_getajobbundle_companytype_add_company"
    Then I should see "n'est pas un email valide."

Scenario: Add a company with a bad zip code (just one number)
    Given I am on "/newcompany"
    When I fill in "mrmcburger_getajobbundle_companytype_name" with "Another Behat Test"
    And I fill in "mrmcburger_getajobbundle_companytype_sector" with "BehatTest Sector"
    And I fill in "mrmcburger_getajobbundle_companytype_address_number" with "12B"
    And I fill in "mrmcburger_getajobbundle_companytype_address_type" with "rue"
    And I fill in "mrmcburger_getajobbundle_companytype_address_name" with "BehatTestAddress"
    And I fill in "mrmcburger_getajobbundle_companytype_address_zip" with "7"
    And I fill in "mrmcburger_getajobbundle_companytype_address_city" with "Behat"
    And I press "mrmcburger_getajobbundle_companytype_add_company"
    Then I should see "Cette valeur n'est pas valide"

Scenario: Add a company with a bad zip code (alphabetic character)
    Given I am on "/newcompany"
    When I fill in "mrmcburger_getajobbundle_companytype_name" with "Another Behat Test"
    And I fill in "mrmcburger_getajobbundle_companytype_sector" with "BehatTest Sector"
    And I fill in "mrmcburger_getajobbundle_companytype_address_number" with "12B"
    And I fill in "mrmcburger_getajobbundle_companytype_address_type" with "rue"
    And I fill in "mrmcburger_getajobbundle_companytype_address_name" with "BehatTestAddress"
    And I fill in "mrmcburger_getajobbundle_companytype_address_zip" with "aa"
    And I fill in "mrmcburger_getajobbundle_companytype_address_city" with "Behat"
    And I press "mrmcburger_getajobbundle_companytype_add_company"
    Then I should see "Cette valeur n'est pas valide"

Scenario: Modify a company
    Given I am on "/modifycompany/BehatTest"
    And I fill in "mrmcburger_getajobbundle_companytype_sector" with "BehatTest Sectora"
    And I fill in "mrmcburger_getajobbundle_companytype_address_number" with "12A"
    And I fill in "mrmcburger_getajobbundle_companytype_address_type" with "allée"
    And I fill in "mrmcburger_getajobbundle_companytype_address_name" with "BehatTest Addressa"
    And I fill in "mrmcburger_getajobbundle_companytype_address_additional" with "additionala"
    And I fill in "mrmcburger_getajobbundle_companytype_address_zip" with "73"
    And I fill in "mrmcburger_getajobbundle_companytype_address_city" with "Behat"
    And I fill in "mrmcburger_getajobbundle_companytype_numbers" with "numbersa"
    And I fill in "mrmcburger_getajobbundle_companytype_phone" with "phonea"
    And I fill in "mrmcburger_getajobbundle_companytype_mail" with "maila@gmail.com"
    And I fill in "mrmcburger_getajobbundle_companytype_presentation" with "presentationa"
    And I fill in "mrmcburger_getajobbundle_companytype_companycriteria_displacement" with "1"
    And I fill in "mrmcburger_getajobbundle_companytype_companycriteria_celebrity" with "6"
    And I fill in "mrmcburger_getajobbundle_companytype_companycriteria_missionInterest" with "7"
    And I fill in "mrmcburger_getajobbundle_companytype_companycriteria_salaryExpectation" with "8"
    And I fill in "mrmcburger_getajobbundle_companytype_companycriteria_workConditions" with "3"
    And I fill in "mrmcburger_getajobbundle_companytype_companycriteria_evolutionPossibilities" with "2"
    And I press "mrmcburger_getajobbundle_companytype_add_company"
    Then I should see "BehatTest"
    And I should see "BehatTest Sectora"
    And I should see "12A"
    And I should see "allée"
    And I should see "additionala"
    And I should see "73"
    And I should see "BehatTest Addressa"
    And I should see "numbersa"
    And I should see "phonea"
    And I should see "maila@gmail.com"
    And I should see "presentationa"
    And I should see "1"
    And I should see "6"
    And I should see "7"
    And I should see "8"
    And I should see "3"
    And I should see "2"

Scenario: Modify a company with a bad e-mail address
    Given I am on "/modifycompany/BehatTest"
    And I fill in "mrmcburger_getajobbundle_companytype_sector" with "BehatTest Sector"
    And I fill in "mrmcburger_getajobbundle_companytype_address_number" with "12B"
    And I fill in "mrmcburger_getajobbundle_companytype_address_type" with "rue"
    And I fill in "mrmcburger_getajobbundle_companytype_address_name" with "BehatTestAddress"
    And I fill in "mrmcburger_getajobbundle_companytype_address_zip" with "72"
    And I fill in "mrmcburger_getajobbundle_companytype_address_city" with "Behat"
    And I fill in "mrmcburger_getajobbundle_companytype_mail" with "FakeAdressMail"
    And I press "mrmcburger_getajobbundle_companytype_add_company"
    Then I should see "n'est pas un email valide."

Scenario: Modify a company with a bad zip code (just one number)
    Given I am on "/modifycompany/BehatTest"
    And I fill in "mrmcburger_getajobbundle_companytype_sector" with "BehatTest Sector"
    And I fill in "mrmcburger_getajobbundle_companytype_address_number" with "12B"
    And I fill in "mrmcburger_getajobbundle_companytype_address_type" with "rue"
    And I fill in "mrmcburger_getajobbundle_companytype_address_name" with "BehatTestAddress"
    And I fill in "mrmcburger_getajobbundle_companytype_address_zip" with "7"
    And I fill in "mrmcburger_getajobbundle_companytype_address_city" with "Behat"
    And I press "mrmcburger_getajobbundle_companytype_add_company"
    Then I should see "Cette valeur n'est pas valide"

Scenario: Modifiy a company with a bad zip code (alphabetic character)
    Given I am on "/modifycompany/BehatTest"
    And I fill in "mrmcburger_getajobbundle_companytype_sector" with "BehatTest Sector"
    And I fill in "mrmcburger_getajobbundle_companytype_address_number" with "12B"
    And I fill in "mrmcburger_getajobbundle_companytype_address_type" with "rue"
    And I fill in "mrmcburger_getajobbundle_companytype_address_name" with "BehatTestAddress"
    And I fill in "mrmcburger_getajobbundle_companytype_address_zip" with "aa"
    And I fill in "mrmcburger_getajobbundle_companytype_address_city" with "Behat"
    And I press "mrmcburger_getajobbundle_companytype_add_company"
    Then I should see "Cette valeur n'est pas valide"
